name: pomodoro_kanban
description: A Kanban board with Pomodoro timer
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  logger: ^2.0.2
  path: ^1.8.3
  uuid: ^3.0.6
  provider: ^6.1.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.1
  path_provider: ^2.1.2
  intl: ^0.17.0
  flutter_local_notifications: ^17.0.0
  drag_and_drop_lists: ^0.4.2
  animate_do: ^3.3.4
  csv: ^5.1.1
  pdf: ^3.10.8
  firebase_analytics: ^10.8.0
  fl_chart: ^0.65.0
  collection: ^1.17.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
