// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTerOxrDA3zWyLOgQkAFnYjFd_kcl7Ct4',
    appId: '1:163597134525:web:193ac9233e3967327725d4',
    messagingSenderId: '163597134525',
    projectId: 'kanban-pomodoro',
    authDomain: 'kanban-pomodoro.firebaseapp.com',
    storageBucket: 'kanban-pomodoro.firebasestorage.app',
    measurementId: 'G-EEQ3Z8LZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuc6Mfe_tN8ntPIZkJcUU5_vcaZWr9tE',
    appId: '1:163597134525:android:dde7164227b5a4477725d4',
    messagingSenderId: '163597134525',
    projectId: 'kanban-pomodoro',
    storageBucket: 'kanban-pomodoro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVaZ4fw7RzLdUKMGW1-e8kynM-dOz580',
    appId: '1:163597134525:ios:22e59acbbc5ce7c37725d4',
    messagingSenderId: '163597134525',
    projectId: 'kanban-pomodoro',
    storageBucket: 'kanban-pomodoro.firebasestorage.app',
    iosBundleId: 'com.example.kanbanPomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVaZ4fw7RzLdUKMGW1-e8kynM-dOz580',
    appId: '1:163597134525:ios:22e59acbbc5ce7c37725d4',
    messagingSenderId: '163597134525',
    projectId: 'kanban-pomodoro',
    storageBucket: 'kanban-pomodoro.firebasestorage.app',
    iosBundleId: 'com.example.kanbanPomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTerOxrDA3zWyLOgQkAFnYjFd_kcl7Ct4',
    appId: '1:163597134525:web:5ac4e35af74de6767725d4',
    messagingSenderId: '163597134525',
    projectId: 'kanban-pomodoro',
    authDomain: 'kanban-pomodoro.firebaseapp.com',
    storageBucket: 'kanban-pomodoro.firebasestorage.app',
    measurementId: 'G-4952EP6MPJ',
  );
}
